### ISSUE TITLE
Docs: Create a developer landing page for Aspects / Analytics

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#103]
Currently https://openedx.org/community/documentation/ has a missing link to the Insights API. We should:

- Create a top level "developer" Aspects page with links to appropriate other pages in this epic and the data models
- Create an anaytics top level page in docs.openedx.org with links to:
  - Tracking log documentation / event list
  - Aspects / aspects developer docs
- Request an update to the openedx.org link above to link out to the high level pages above

**Comment by Ian2012** [comment]
Does this still applies or the other documentation is enough?

**Comment by bmtcril** [comment]
Looks like this has been changed in the meantime, so it should be fine.
