### ISSUE TITLE
Operator dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#121]
Clean up the Operator dashboard to make the UI and filters consistent, and fix performance issues

- [x] #198
- [x] #199
- [x] #200

**Comment by Ian2012** [comment]
Work in progress: https://github.com/openedx/tutor-contrib-aspects/pull/617

**Comment by crathbun428** [comment]
@Ian2012 and @bmtcril - would we say this ticket is still in development or should I move this ticket to done on our Kanban board? If not complete yet, feel free to give me a head's up so that I can move it over or feel free to move this to done when it's complete.

**Comment by crathbun428** [comment]
Totally fine - just wanted to make sure I'm updating this board where we can.

**Comment by bmtcril** [comment]
These changes are merged, hopefully good enough!
