### ISSUE TITLE
Discovery work is conducted to determine if a user can download a CSV of the tabular view of each visualization if reports are embedded into the LMS

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#122]

**Comment by Ian2012** [comment]
Hi @crathbun428, the Discovery work has been conducted in this [doc](https://docs.google.com/document/d/1SnOrpBZvHO6VcLDlZCRfay4y2BH3zCQnFEx7mJXInmM/edit?usp=sharing): 

A product review is needed

**Comment by bmtcril** [comment]
Assigning to @crathbun428 for review

**Comment by crathbun428** [comment]
@Ian2012 - This looks good to me. Can I confirm that this work **won't expand** what users can view and/or download the CSV files for course level data in Superset, correct?

**Comment by crathbun428** [comment]
@Ian2012 - excellent. Thanks for confirming!
