### ISSUE TITLE
Data pipelines for course dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#124]

**Comment by bmtcril** [comment]
I can't think of anything. Can you take a spin through the chart tasks and make suggestions for the datasets that we expect to support them?

**Comment by SoryRawyer** [comment]
Sure thing

**Comment by crathbun428** [comment]
@SoryRawyer - would we say the data pipelines for the course dashboard are still in development or should I move this ticket to done on our Kanban board? If not complete yet, feel free to give me a head's up so that I can move it over or feel free to move this to done when it's complete.

**Comment by SoryRawyer** [comment]
Sorry for missing this! I think we can call this done. I'm making a final pass now to make sure each chart respects the cross-filters, but I don't think that should hold us back from closing this ticket.
