### ISSUE TITLE
User can view enrollment breakdown for course

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#128]
**User Story**
As a course author, I want to view details of the enrollment breakdown for my course, so that I know who is in my course, what enrollment track they're on (when applicable), and I am able to compare the enrollment for this course against my other courses.

**Acceptance Criteria**
Scenario: A course author can view enrollment information for their course from the course dashboard
**Given I** am a course author with X permissions
**When I** navigate to the course dashboard
**Then I** can see the **number of total learners enrolled** in my course
**And I** can see the **number** and **percent of total enrollees** for current enrollees and enrollees per enrollment track (of enrollment tracks available on my instance)
**And when** an enrollment track is not available on my instance
**Then I** don't see it listed in the enrollment data for my course dashboard

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_enrollments` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments.yaml) in Superset.
