### ISSUE TITLE
User can view enrollment rate information for course plotted over time

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#129]
**User Story**
As a course author, I want to view the enrollment rate information for my course plotted over time, so that I am able to view steep climbs in enrollment as one way of identifying when and how learners are finding out about and signing up for my course.

**Acceptance Criteria**
Scenario: A course author views the enrollment rate chart from the course dashboard
**Given I** am a course author with X permissions
**When I** view the enrollment rate chart on the course dashboard
**Then I** see the number of learners enrolling in my course plotted over time
**And I** am able to clearly identify date and date ranges easily from the chart

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_enrollments_by_day` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml) in Superset.
