### ISSUE TITLE
User can view the change in number of enrollees enrolled in the past week (default)

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#130]
**User Story**
As a course author, I want to view the change in the number of enrollees in my course over the past week, so that I can view recent enrollment activity at a glance from the course dashboard.

**Acceptance Criteria**
Scenario: A course author can view the change in enrollment over the past week from the course dashboard
**Given I** am a course author with X permissions
**When I** look at the change in enrollment information in the enrollment section of the course dashboard
**Then I** can see the number of enrollees who enrolled in the course over the past week

**Comment by SoryRawyer** [comment]
I think this can be charted using the [fact_enrollments_by_day dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml) in Superset.
