### ISSUE TITLE
User can view a detailed breakdown of the number and percentage of enrollees per enrollment track (of the enrollment tracks available on my Open edX instance) enrolled in the past week

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#131]
**User Story**
As a course author, I want to view a detailed breakdown of the learners who enrolled in my course over the past week, so that I can view any recent changes or trends in enrollment track activity easily from the course dashboard.

**Acceptance Criteria**
Scenario: A course author can view the change in enrollment over the past week from the course dashboard
**Given I** am a course author with X permissions
**When I** look at the change in enrollment information in the enrollment section of the course dashboard
**Then I** can see the number and percentage of enrollees who enrolled in the course over the past week by enrollment track (of the enrollment tracks available on my instance)

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_enrollments` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments.yaml) in Superset.
