### ISSUE TITLE
If discovery determines that embedding the dashboard are feasible, Course-level dashboard is embedded into the Open edX LMS Instructor tab

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#133]
**User Story**
As a course author, I want the course level reports embedded into the Open edX LMS instructor dashboard, so that I don't need to navigate to Superset to view the data about my course.

**Acceptance Criteria**
Scenario: A course author can view the existing course-level reports from the LMS instructor dashboard
**Given I** am a course author with X permissions
**When I** navigate to the LMS instructor dashboard
**Then I** am able to navigate to a dashboard within the LMS labeled Aspects Reports for my course
**And when I** open the course dashboard
**Then I** see all existing course-level reports for my course
**And I** am able to download a CSV file of the tabular view of the data used to create any report on the dashboard from the LMS

**Comment by bmtcril** [comment]
This should be all set
