### ISSUE TITLE
User sees the number of learners in course who have a passing grade or higher

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#140]
**User Story**
As a course author, I want to see the number of learners who have a passing grade or higher in my course, so that I have a sense of how many learners have passed my course to date at a glance alongside the rest of the course-level metrics.

**Acceptance Criteria**
Scenario: A course author can see the number of learners that have a passing grade or higher in their course from the course dashboard
**Given I** am a course author with X permissions
**When I** view the learner performance section of the course dashboard
**Then I** can see the number of learners who have a passing grade or higher in my course to date

**Comment by SoryRawyer** [comment]
@bmtcril apologies if this was already answered elsewhere, but is "passing grade" defined somewhere? Is that a static value across all classes, or could this be defined per course?

**Comment by bmtcril** [comment]
I think the best path to determining this is looking at the `now_passed` / `now_failed` events and seeing which one is most recent. If there is none, they haven't passed. https://github.com/openedx/event-routing-backends/blob/master/event_routing_backends/processors/xapi/event_transformers/enrollment_events.py

**Comment by SoryRawyer** [comment]
Are those events sent to ClickHouse? I don't think I see those events after trying a few questions in the demo course.

**Comment by bmtcril** [comment]
You'll have to do it in a graded section to trigger it, I believe. 

We do have passed/failed events in the beta server:
```
┌─verb_id───────────────────────────────┬─cnt─┐
│ http://adlnet.gov/expapi/verbs/passed │  45 │
└───────────────────────────────────────┴─────┘

┌─verb_id───────────────────────────────┬─cnt─┐
│ http://adlnet.gov/expapi/verbs/failed │ 189 │
└───────────────────────────────────────┴─────┘
```

**Comment by bmtcril** [comment]
The "Homework Question Styles" section in the demo course should trigger it, I think.
