### ISSUE TITLE
User sees the distribution of the current course grade of all learners the course

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#141]
**User Story**
As a course author, I want to see a distribution of current course grades for all the learners in my course, so that I can view this information alongside other learner performance metrics for my course.

**Acceptance Criteria**
Scenario: A course author sees the distribution of current course grades for all learners in their course on the course dashboard
**Given I** am a course author with X permissions
**When I** view the learner performance section of the course dashboard
**Then I** see a distribution of current course grades for the learners in my course

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_problem_grades` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_grades.yaml) in Superset.
