### ISSUE TITLE
User sees performance details for each assignment in the course

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#142]
**User Story**
As a course author, I want to view learner performance details for each assignment in my course, so that I know how many learners have attempted the assignment to date and can see how learners are performing on the assignment on average.

**Acceptance Criteria**
Scenario: A course author can see the number of learners who have attempted each assignment and how those learners are have performed on the assignment on average
**Given I** am a course author with X permissions
**When I** view the performance section of the course dashboard
**Then I** see the number of learners who have attempted at least one problem in each assignment
**And** the average breakdown of correct versus incorrect responses to the assignment across all learners who attempted the assignment in the course

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_problem_grades` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_grades.yaml) in Superset. The [`fact_learner_problem_summary` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml) could also show information about attempt history and the number of hints shown.
