### ISSUE TITLE
User sees the number of learners who attempted each graded and ungraded problem

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#143]
**User Story**
As a course author, I want to see the number of learners who attempted each graded and ungraded problem in my course, so that I see which problems learners are trying from my course.

**Acceptance Criteria**
Scenario: A course author can view how many learners attempted each problem in their course
**Given I** am a course author with X permissions
**When I** view the performance section of the course dashboard
**Then I** can view the number of learners who attempted each graded and ungraded problem in my course

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_problem_responses` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_responses.yaml) in Superset.
