### ISSUE TITLE
User sees the average number of attempts taken for each graded and ungraded problem

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#145]
**User Story**
As a course author, I want to see the average number of attempts taken to answer each problem in my course, so I have another way to determine problem difficulty.

**Acceptance Criteria**
Scenario: A course author sees the average number of attempts taken to answer each problem in the course on their course dashboard
**Given I** am a course author with X permissions
**When I** view the performance section of the course dashboard
**Then I** see the average number of attempts taken to answer each graded and ungraded problem in the course

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_problem_responses` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_responses.yaml) in Superset.
