### ISSUE TITLE
Data pipelines for learner group reports

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#146]

**Comment by crathbun428** [comment]
@SoryRawyer - Hi Rory. Curious about Learner Group Reports data pipelines. Are these in progress or no, not yet? Just hoping to update the board, if needed. Thanks!

**Comment by SoryRawyer** [comment]
Sorry for missing this! Yes, this is in progress now. I'll have an update tomorrow at our check-in.
