### ISSUE TITLE
User can navigate to a learner group dashboard from the rest of their course data that clearly lays out the criteria used to build the learner group

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#150]
**User Story**
As a course author, I want to be able to view a set of reports regarding the enrollment, engagement, and performance for a group of learners in my course from the course dashboard, so that I have an easy way of viewing course information for a potentially at-risk subset of learners in my course. 

**Acceptance Criteria**
Scenario: A course author can navigate to a set of reports for a learner group from the course dashboard that clearly outlines the criteria used to create the learner group
**Given I** am a course author with X permissions
**When I** am on the course dashboard for my course
**Then I** am able to navigate to a set of reports for a learner group
**And** it is clear to me what criteria was used to define the learner group (outlined in Notes, below)

**Notes**
Attributes used to create the pre-set learner group
1. have enrolled in the course
2. AND have not visited the course in 7 or more days
3. AND have not yet passed the course
4. AND who have visited a page other than the course homepage OR watched a video OR answered a graded or ungraded problem OR posted in the course discussion forum

**Comment by SoryRawyer** [comment]
Looking back through the project Slack channel, I saw Brian post an updated list of criteria for defining "at-risk":
- have enrolled in the course
- AND have not visited the course in 7 or more days
- AND have not yet passed the course
- AND who have visited a page other than the course homepage

The rationale for simplifying the last criterion was that to watch a video or post in the forum or answer a question would require visiting a page other than the homepage first.

Does this still seem like a reasonable adjustment?

**Comment by crathbun428** [comment]
@SoryRawyer - Yes, that's exactly right. Basically we want the learner to have done something in the course other than visit the homepage (that includes watching a video or answering a problem or posting in the forum, etc). Thanks for confirming.

cc: @bmtcril
