### ISSUE TITLE
Review the currently supported xAPI events

### ISSUE THREAD

**Issue by e0d** [openedx/openedx-aspects#18]
Perform a holistic review of the [currently supported xAPI events](https://github.com/openedx/event-routing-backends/blob/master/docs/event-mapping/Supported_events.rst) to ensure that

- They are sufficient to support existing analytics systems used by the community
- They conform to the data model for any related profiles, e.g., [the video profile](https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html).

AC:

- a backlog of:
  - events that should be made supported at the xAPI layer
  - changes to events required to conform with ADL profiles

**Comment by bmtcril** [comment]
I think this is set for v1
