### ISSUE TITLE
Capture tags in ClickHouse on course publish

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#217]
Tagging is coming soon, we should make sure that anyone running with tags gets them captured to ClickHouse even if we're not using them in reporting yet. We should set up a test environment with tagging enabled and confirm that any tags get passed through, and nothing errors if they are not present. 

I expect we should be able to get the tags here: https://github.com/openedx/platform-plugin-aspects/blob/main/platform_plugin_aspects/sinks/course_overview_sink.py#L97

**Comment by pomegranited** [comment]
@bmtcril Tags are not versioned in the same way as courses are -- versioning was out of scope for the MVP -- so tags on blocks/courses can change independently of course publish.

Do you still want tags to sync only on course publish, or can they sync independently as they're created/deleted?
