### ISSUE TITLE
Add basic enrollment and pass rate information to Course Comparison dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#243]
**User Story**
As a course delivery team member, I want to be able to compare the learner enrollment information across courses and course runs, so that I am able to easily identify the most and least popular courses without having to go into each course dashboard. 

**Acceptance Criteria**
**Given I** have access to the Course Comparison dashboard
**When I** view the Course Comparison dashboard
**Then I** can easily view and sort by the following metrics for the courses (or course runs) I am able to compare in the dashboard:

- Count of total current enrollees
- Count of enrollees per enrollment track **of the tracks available on my instance**

**Note:** See screenshot below of the enrollment counts table. The Active in the Past 7 days metric will be added in a future user story.

![Screenshot 2024-08-28 at 10 42 00 AM](https://github.com/user-attachments/assets/2d46653f-8cd2-412b-930a-7ea33c5c72da)

**Comment by saraburns1** [comment]
![Image](https://github.com/user-attachments/assets/26bfccc9-84ed-427e-ba47-9bfcbfb9e3e3)
