### ISSUE TITLE
Add active within 7 days count to Course Comparison dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#244]
**User Story**
As a course delivery team member, I want to be able to compare the number of learners active in the past 7 days across courses and course runs, so that I am able to easily spot the courses currently seeing the most and least engagement without having to go in to each course dashboard.

**Acceptance Criteria**
**Given I** have access to the Course Comparison dashboard
**When I** view the Course Comparison dashboard
**Then I** can easily view and sort by the number of learners active within the last 7 days (see note) for the courses (or course runs) I am able to compare in the dashboard. (See screenshot below showing where in the dashboard this column should appear): 

![Screenshot 2024-08-28 at 10 42 00 AM](https://github.com/user-attachments/assets/91e56937-a844-4d93-8ce2-1c877fe038b8)

**Note**
The number of learners active within the last 7 days can be called **Active within last 7 days** on the dashboard and represents the count of learners who did something (viewed a unit page, answered a problem, watched a video) in the course (other than visit the course homepage) within the last 7 days.

**Comment by saraburns1** [comment]
![Image](https://github.com/user-attachments/assets/b4bd2d5e-66dd-42b4-a16c-818cc9e48f56)
