### ISSUE TITLE
Add a course-level tag filter to the course comparison dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#248]
**User Story**
As a course delivery team member, I want to be able to compare only courses that have specified course-level tag(s), so that I can compare courses that share something in common (subject matter, competency, etc). 

**Acceptance Criteria**
**Given I** have access to the Course Comparison dashboard
**When I** view the Course Comparison dashboard
**Then I** see that I am able to filter the courses or course runs by Course-level tag(s)
**And** I am able to search for and select one or more values when applying the filter

**And when I** apply the filter, I see the course comparison dashboard update to filter and display results including only courses or course runs that match the applied filter (see note for examples and details about course tags). 

**Notes**

1. If a user selects the Microbiology tag to apply it to a course and the taxonomy used for that instance has a hierarchy in place (example: Biology/Microbiology), both the Biology and Microbiology tags will be applied.
2. If a user selects multiple course tags (for example 2 course tags) when creating a course tag filter, the results show any result that has tag value 1 OR tag value 2.
3. If a user wants to compare all courses with the Microbiology tag, they should be comparing all courses with the Microbiology tag regardless of any other tags that may be applied to those courses (for example: courses that are being analyzed may have just Biology/Microbiology applied, some may have the Biology/Microbiology and Biology/Microbiology/Microbiomes tags applied) and that’s OK, both should appear in the results for this filter.

**Comment by Ian2012** [comment]
The following PRs are in progress for this work:
- Tag Sink: https://github.com/openedx/platform-plugin-aspects/pull/82
- Course Tag dataset: https://github.com/openedx/aspects-dbt/pull/118
- Tag Tables / Integration Test: https://github.com/openedx/tutor-contrib-aspects/pull/927

**Comment by saraburns1** [comment]
![Image](https://github.com/user-attachments/assets/7f3c45f7-8e43-4ed6-a3c6-9bb072ae8c8f)

**Comment by Ian2012** [comment]
@saraburns1 Can you constrain the tags column to at most 32~46 chars?

**Comment by saraburns1** [comment]
Hmm from #249 `And when there are more than N characters to be shown, we truncate this list (but allow the user some way of viewing the whole list (maybe on hover or clicking to expand/collapse).`

I don't know of a way to do this, do you @Ian2012 ? I could truncate it within the sql but there wouldn't be an option to expand it.

**Comment by Ian2012** [comment]
We are use to truncate those values with SQL, I didn't knew superset allow it to truncate it too. If Superset UI doesn't get unusable on large values I guess we can keep it as you have it right now

**Comment by saraburns1** [comment]
Going to try it with a scroll bar at the bottom and see what the feedback is 

![image](https://github.com/user-attachments/assets/4d803f53-3651-4fde-a6cd-700fa10deb65)
