### ISSUE TITLE
Add a helper text or some indicator near the course-level tag filter that it is compatible with Redwood+

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#250]
**User Story**
As an Aspects delivery team member, I want to indicate to Operators who have downloaded the most recent version of Aspects and are viewing the Course Comparison dashboard that the Course-level tag filter is compatible with Redwood+, so that I can make it clear to Operators using the Course Comparison dashboard on a Open edX Release before Redwood that the Course-level tag filter won't work for their instance and why.

**Acceptance Criteria**
**Given I** have access to the Course Comparison dashboard
**When I** go to use the Course-level filter dashboard
**Then I** am notified in some way near the filter that this filter is compatible with the Redwood Release and after.

**Comment by Ian2012** [comment]
@crathbun428 This is already created, can you confirm to close this task?

**Comment by crathbun428** [comment]
@Ian2012 - Looks good to me. Closing now.
