### ISSUE TITLE
Test the performance of the course-level tag filter

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#251]
**User Story**
As a Aspects developer, I want to test the performance of the Course-level tag(s) filter, its performance returning results, and capture any areas of the dashboard that need improvement, so that I can confirm the dashboard renders all required data and renders it in an acceptable amount of time and I make sure to document performance enhancements work that is needed to improve problem areas.

**Acceptance Criteria**
**Given I** am an Aspects developer
**When I** test the performance of the Course-level tag filter
**Then I** see that the filter behaves as expected (I can search for course-level tags, I can select one or more) and all expected results render render
**And I** capture any areas that are in need of critical performance improvement.

**Comment by crathbun428** [comment]
@bmtcril and @saraburns1 - Same question as I posted on the performance user story for the first epic I added today.

**Comment by Ian2012** [comment]
The tagging dataset was implemented using dictionaries similar to course_names, and it's prepared in a superset's virtual dataset. Given that I don't think the performance is a concern right now and we can close this one @bmtcril

**Comment by bmtcril** [comment]
My only concern off hand is how big the dictionaries may grow, but we should be able to test the rest as part of the dashboard testing.
