### ISSUE TITLE
Test the performance of the Problem tabs on the Individual and At-Risk Learner Dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#256]
**User Story**
As a Aspects developer, I want to test the performance of the updated Individual and At-Risk Learners dashboard and capture any areas of the dashboard that need improvement, so that I can confirm the dashboard renders all required data and renders it in an acceptable amount of time and I make sure to document performance enhancements work that is needed to improve problem areas.

**Acceptance Criteria**
**Given I** am an Aspects developer
**When I** test the performance of the updated At-Risk Learners and Individual Learner dashboards
**Then I** see that the dashboard and all required charts and tables render
**And I** capture any areas that are in need of critical performance improvement.

**Comment by crathbun428** [comment]
@bmtcril and @saraburns1 - Same question as I posted on the performance user story for the first epic I added today.
PLUS: Does it make sense to have a performance story for this epic alone (or after all 3 course-level dashboard improvement epics are completed?). Leaving this for now since my gut tells me it may make sense to test this incrementally. Let me know if you think.

**Comment by Ian2012** [comment]
All of this has been improved here: https://github.com/openedx/tutor-contrib-aspects/pull/953 https://github.com/openedx/tutor-contrib-aspects/pull/952 https://github.com/openedx/tutor-contrib-aspects/pull/957
