### ISSUE TITLE
Investigation: Superset Permissions and Dashboards

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#28]
We will need some default dashboards, depending on the permissions level of the user. I'd like to make sure we can create direct link to different dashboards and allow some kind of navigation between org level dashboards and between different courses.

If we don't have Superset permissions working in ClickHouse yet, we should be able to use this Tutor plugin to get a jump start on this task using the LMS MySQL database as a backend: https://github.com/open-craft/tutor-contrib-superset/ . Currently you need to install this from the working branch `pip install git+https://github.com/open-craft/tutor-contrib-superset/@jill/install-superset` before following the other install directions.

We would like to support the following user roles:

- Site operator - managed in Superset
- Org analyst - managed in LMS? I think the prototype handles this, I'm not sure how off hand
- Course instructor - managed in LMS
- Course analyst - managed in Superset? I don't think LMS has data to say "can view course data but not have Studio access"

We would like to support the following dashboards:

- Admin dashboards (data across all orgs / courses) - preferably with links down to dashboards for each org
- Org dashboard (data across all courses for an org) - preferably with links down to dashboards for each course
- Course dashboard (data for one specific course)

We would like to enforce the following permissions for each type of dashboard:

- Admin dashboard (Superset "Admin" role)
  - Can create data sources, queries, reports, manage users, etc.
  - Roles: Site operator

- Org dashboard / datasources (Superset "Gamma" role?)
  - Can view the org dashboard
  - Can view every course dashboard in the org
  - Roles: Site operator, Org analyst

- Course dashboard / datasources (Superset "Gamma" role)
  - Can view the dashboard for a course
  - Roles: Site operator, Org analyst, Course Instructor (for courses they own), Course analyst (for courses they're allowed)

AC:
- At least 4 dashboards: Admin, Org, and 2 courses in different orgs
- Users for each role, including instructors that can only access 1 course each
- Permissions limiting access to each dashboard as outlined above
- Documentation of exactly how this was configured, using which data sources, and with example code or (preferably) updates to the tutor-contrib-superset repo to support this permissions scheme
- If aspects of this can't be done, comment on this ticket and try to provide options for how we might support the missing functionality going forward

**Comment by Ian2012** [comment]
@bmtcril I will close this issue since this has been implemented
