### ISSUE TITLE
Video engagement chart does not appear on all 3 course-level dashboards and tables appear empty on individual learner dashboard

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-aspects#290]
**Steps to Reproduce:**

- On the...
   - Course dashboard and At-Risk Learner dashboard, navigate to Engagement/Videos
   - Individual Learner dashboard, navigate to Videos
- View the first chart on the page labeled: Video Engagement per Section/Subsection
- On the Individual Learner dashboard, view the Video Engagement per Section and Video Engagement per Subsection tables

**Expected Results:**
As long as there has been engagement in the course:

1. I can view learner engagement with the videos in this course on the Video Engagement per Section/Subsection chart (similar to how I can for this graph on the Pages and Problems tabs)
2. I can see information populated in the video engagement per section and video engagement per subsection tables on the Individual learner dashboard (like how I can for the course and at-risk learner dashboards)

**Actual Results:**
Even though there has been learner engagement with the videos in this course, the graph appears empty on all 3 course-level dashboards and the tables appear empty on the individual learner dashboard (see screenshot, below):

![Screenshot 2024-10-21 at 11 59 34 AM](https://github.com/user-attachments/assets/ab644cf7-5d94-4531-94b0-3aec9973db58)

![Screenshot 2024-10-21 at 2 34 15 PM](https://github.com/user-attachments/assets/d0fbfb4d-7ab6-4ef8-8b73-40594d97eec6)

Note: For reference, I found this issue on the Test Course Comparison Dashboard course dashboards on the Open edX organization on the Axim-2 sandbox.

**Comment by saraburns1** [comment]
This is working for engagement going forward (will not include previous data)
![Image](https://github.com/user-attachments/assets/47c9deb9-067c-4898-87fe-72cf862b35a0)
