### ISSUE TITLE
Docs: Create initial documentation

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#57]
For v1 we want to create the following documents:

- [x] #77
- [ ] #78
- [ ] #79
- [ ] #80
- [ ] #81
- [ ] #82
- [ ] #83
- [ ] #101
- [ ] #103 
- [ ] #108 
- [x] #61
- [x] #68
- [x] #73
- [x] #75
- [x] #58
- [x] #60
- [x] #59
- [x] #62
- [x] #63
- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #74
- [x] #76
- [x] #84

**Comment by Apgomeznext** [comment]
Aspects Documentation Project: https://docs.google.com/document/d/1YA1omBDqOkbFSCcoXaxc6gGVcDqm4vIghmej-6tvm38/edit#heading=h.ndsf89cg7q43
