### ISSUE TITLE
Docs: Update ADRs

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#61]
Update [existing ADRs](https://github.com/openedx/openedx-aspects/tree/main/docs/decisions):

- [x] Minor updates to reword "OARS" as "Aspects": https://github.com/openedx/openedx-aspects/pull/104
- [x] Supersede [6. Areas of responsibility](https://github.com/openedx/openedx-aspects/blob/main/docs/decisions/0006_areas_of_responsibility.rst) with a single tutor plugin repo instead: https://github.com/openedx/openedx-aspects/pull/105

Add new ADRs for:

- [x] Protections for PII: https://github.com/openedx/openedx-aspects/pull/106
- [x] Internationalization/localization/translations: https://github.com/openedx/openedx-aspects/pull/107, https://github.com/openedx/openedx-aspects/pull/110
- [x] Course tree data https://github.com/openedx/openedx-aspects/pull/109
- [x] Division of responsibilities between clickhouse and dbt: https://github.com/openedx/openedx-aspects/pull/112
- [x] Don't use JSON field in clickhouse -- all useful data should be pulled out into MV fields. https://github.com/openedx/openedx-aspects/pull/113

**Comment by pomegranited** [comment]
@bmtcril I've reviewed the [existing ADRs](https://github.com/openedx/openedx-aspects/tree/main/docs/decisions) and found most of them to still be accurate, but these updates are worth doing:

* Most need minor updates to reword "OARS" as "Aspects".
* [6. Areas of responsibility](https://github.com/openedx/openedx-aspects/blob/main/docs/decisions/0006_areas_of_responsibility.rst) references multiple tutor plugins (tutor-contrib-clickhouse, tutor-contrib-ralph, tutor-contrib-superset).
  This ADR should reflect the consolidated structure chosen for https://github.com/openedx/tutor-contrib-aspects

I think ADRs for these topics could be added:

* Protections for PII
* Internationalization/localization/translations
* Course tree data
* Materialized views stored in dbt: https://github.com/openedx/tutor-contrib-aspects/issues/533)
* Don't use JSON field in clickhouse -- all useful data should be pulled out

Do you agree? Are there any other decisions you'd like me to write up?

**Comment by bmtcril** [comment]
I think these are great, there are probably more but I'll add them as their own tasks if need be. Thanks for tackling this!

**Comment by pomegranited** [comment]
Huge thanks to you, @Ian2012 and @bmtcril , for your guidance and reviews on these PRs!
Closing this issue.
