### ISSUE TITLE
Docs: How-to - xAPI Transforms

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#75]

**Comment by pomegranited** [comment]
Topics to address:

* xAPI transforms in event-routing-backends
* xAPI transforms in Ralph vs Aspects
* recommended method for transforming non-openedx events (see https://github.com/openedx/event-routing-backends/pull/377)

**Comment by bmtcril** [comment]
I think just a couple of lines about choosing Verb/Object pairs, and a reminder that the paradigm is "Actor does Verb on Object" for helping to understand why there are so many similar verbs.
