### ISSUE TITLE
Docs: How-to - Scaling - Superset

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#79]

**Comment by pomegranited** [comment]
From [comment](https://github.com/openedx/openedx-aspects/issues/78#issuecomment-1910258866):

> ...double check that we could override both the MySQL database and redis cache for it if it becomes too resource intensive to share with LMS/Studio

Before we can document this, we need to add some variables to tutor-contrib-aspects, and use them to support a separate MySQL db and redis cache:

* `SUPERSET_DB_ROOT_USERNAME: {{ MYSQL_ROOT_USERNAME }}`
* `SUPERSET_DB_ROOT_PASSWORD: {{ MYSQL_ROOT_PASSWORD }}`
* `SUPERSET_REDIS_HOST: {{ REDIS_HOST }}`
* `SUPERSET_REDIS_PORT: {{ REDIS_PORT }}`
* `SUPERSET_REDIS_PASSWORD: {{ REDIS_PASSWORD }}`

**Comment by Ian2012** [comment]
can we mark this as closed: https://docs.openedx.org/projects/openedx-aspects/en/latest/technical_documentation/how-tos/production_configuration.html

**Comment by bmtcril** [comment]
I think that's enough for now and we can add to it if people have questions. Nothing has come up yet, though.
