### ISSUE TITLE
Supporting Product Research for Aspects (formerly OARS) v1

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/openedx-aspects#8]
What do users expect in terms of feeding data back into studio or LMS? What do they want to see? What are the expectations?

**Comment by bmtcril** [comment]
I think Chelsea has handled this and it's all captured in the v1 PRD https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3988160641/Aspects+V1+Product+Requirements
