### ISSUE TITLE
WIP task: Create an Aspects plugin for small Campus installs

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#86]
In order to exercise, find issues with, and demonstrate the capabilities of expanding Aspects we should create an example (hopefully eventually useful) plugin for it that exercises each extension point. We know that there are some reports which are more useful in smaller scale settings. It doesn't need to do everything to support that use case, but rather use each extension point to create a "campus" dashboard which provides some amount of useful data. This is all just a suggestion, but the attempt is to exercise as much extensibility as possible.

It should use each of these extension points: https://docs.openedx.org/projects/openedx-aspects/en/latest/concepts/extensions.html to do the following:

- [ ]  (optional, this isn't documented yet) Create a custom processor for event-routing-backends to transform an event that ERB doesn't currently handle, such as page views.
- [ ] Create custom ClickHouse SQL that connects to a MySQL database's External ID and auth_user tables to allow re-identifying learners in Superset
- [ ] Create a dbt package with a least one additional view using the new ERB event, or creating a useful dataset that re-identifies the learner by their username
- [ ] Create a RLSF / Filter / Role for the new dataset to only allow course instructors to see the new data
- [ ] Create Superset Assets for a dataset, slice, and dashboard that house the new report

The end goals are: 
- Make sure that all of these extension points work through dev / local / k8s
- Create issues for anything that doesn't work, so we can fix them!
- Update any docs that are incorrect or incomplete

**Comment by Ian2012** [comment]
This issue doesn't apply anymore
