### ISSUE TITLE
Feat: Add completion events

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#88]
We would like to track course completion using the `completion` library. Currently the only tracking log events that are pushed related to completions are implicit events from html blocks. Getting these events is going to require the following steps that should be ticketed when we want to pick up this work:

- [x] Update https://github.com/openedx/completion/ to fire tracking log events when completions are saved
- [x] Update event-routing-backends to transform those events to xAPI
- [x] Add completion materialized views in Alembic
- [x] Add completion views to aspects-dbt
- [ ] Add tab / charts to display completion information in instructor dashboard
- [ ] Optional: create a management command to read the completions from the database and send them in a way that we can backfill this data. Firing off fresh tracking events is probably wrong since it will have the wrong timestamp, but we could possibly create fake tracking log entries in a file that can be read in (gross) or directly read from the database and transform to the xAPI outputs (also gross)... alternatively we can just say that this data isn't available before the Completions app was upgraded in your LMS.

**Comment by Ian2012** [comment]
There is a fact_completions model: https://github.com/openedx/aspects-dbt/blob/main/models/completion/fact_completions.sql

**Comment by bmtcril** [comment]
Yeah, I think from my experimenting with visualizations for this we'll probably need some more intermediate models too. If anyone wants to wrap this up, I've got some potentially useful table structures / queries / visualizations.

**Comment by Ian2012** [comment]
Is this still needed?

**Comment by bmtcril** [comment]
I don't think so, it's not on any roadmap to be used at this point. We can add the rest of the supporting functionality when we know how it will be used.
