### ISSUE TITLE
Investigation: Certificate data

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-aspects#90]
This ticket is in support of the v1 reports listed here, but may not be able to be completed by v1: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3834281985/DRAFT+Aspects+V1+Product+Requirements

A lot of work is happening in the certificates space, and there are a number of open questions about which service should own certs / badges. Currently there are [certificate events](https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_logs/student_event_types.html#certificate-events) listed in the docs, but it's unclear if they're still being fired. This task is to work with the folks who are involved in these discussions and as answers become available about the direction of certificates, try to drive towards a system that outputs events that we can ingest.

Updates should go in this ticket, and when decisions are made we should add new implementation tickets to capture and report on the event data.

**Comment by Ian2012** [comment]
Can we close this one? Certificates has not been a priority

**Comment by bmtcril** [comment]
Yes, I don't think we have any plans for this data at this point.
